package tasks.fibonnaci;

import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.List;

import tasks.Client;

public class FibonnaciClient extends Client<List<Integer>> {
	private static final long serialVersionUID = 1L;

	public FibonnaciClient(String domain) throws RemoteException, NotBoundException, MalformedURLException {
		super("Fibonacci", domain);
	}
	
	public static void main(String[] args) throws Exception {
		System.setSecurityManager(new SecurityManager());
		String domain;
		if(args.length==0) {
			domain = "localhost";
		} else {
			domain = args[0];
		}
		
		final FibonnaciClient client = new FibonnaciClient(domain);
		client.begin();
		final List<Integer> value = client.processJob();
//		client.add(); how to print values generated by
		client.end();
	}

}
